### ISSUE TITLE
XPath: need not-equivalence operator  (  elem[ @attr != "value" ]  )

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mremec/omnixml#11]
```
see patch versus "Downloads OmniXML-latest.7z"

```

Original issue reported on code.google.com by `Arioch...@gmail.com` on 11 Dec 2014 at 11:02

Attachments:
* [OmniXMLXPath_NotEQ.patch](https://storage.googleapis.com/google-code-attachments/omnixml/issue-11/comment-0/OmniXMLXPath_NotEQ.patch)

**Comment by the-Arioch** [comment]
fixed by recent pull merge

**Comment by mremec** [comment]
Thanks.
