### ISSUE TITLE
Malformed xml output

### ISSUE THREAD

**Issue by hafedh-trimeche** [mremec/omnixml#19]
Please note after loading this xml file 
[input.txt](https://github.com/mremec/omnixml/files/2922453/input.txt)
 that the output xml using  the procedure Save(const FileName: string; const OutputFormat: TOutputFormat = ofNone); is wellformad 
[well.txt](https://github.com/mremec/omnixml/files/2922454/well.txt)
.But when using the property XML or SaveToStream the output is malformed 
[bad.txt](https://github.com/mremec/omnixml/files/2922455/bad.txt)

**Comment by mremec** [comment]
Hello,

I cannot reproduce it. After loading your input.txt file, both Save and SaveToStream give identical and valid result. I've used Delphi 10.3 upd1 to test.

I can see that there are some differences in well.txt compared to bad.txt, but they seem to be content related i.e. there are some other XML tags inside document.

**Comment by hafedh-trimeche** [comment]
Hi,
The problem solved by wrapping the property XML:
`function TDynXML.GetXML:TXMLString;
var
  Bytes : TStringStream;
begin
  Bytes := TStringStream.Create(FDocument.XML,TEncoding.UTF8);
  Result := Bytes.DataString;
  Bytes.Free;
end;
`
The returned content is UTF8 encoded and well formed.
